# Examen Demo

In [80]:
# Your imports HERE !!!!
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random

## 01
- Dado un diccionario con una lista de nombres de películas y el año concatenado, crear una función que devuelva un DataFrame con dos columnas:
  - Columna 1, el nombre de la película sin el año
  - Columna 2, el año de la película

In [43]:
movies = {'Name': ["Matrix - 1999", "Cadena Perpetua - 1994", "Parasitos - 2019", "Vengadores, Endgame - 2019", "Interstellar - 2014",
                   "Django Desencadenado - 2012", "El Padrino - 1972", "El Caballero Oscuro - 2008", "Erase Una Vez En America - 1984",
                   "El Senyor de los Anillos, La Comunidad del Anillo - 2001"]}
expected_output = pd.DataFrame({'Name':["Matrix", "Cadena Perpetua", "Parasitos", "Vengadores, Endgame", "Interstellar", "Django Desencadenado",
                                        "El Padrino", "El Caballero Oscuro", "Erase Una Vez En America", "El Senyor de los Anillos, La Comunidad del Anillo"],
                                'Year':["1999", "1994", "2019", "2019", "2014", "2012", "1972", "2008", "1984", "2001"]})
output = extract_year(movies)   # This will call your function extract_year
display(output)
assert(expected_output.equals(output))  # This will fail if the result is not as expected

                                                Name  Year
0                                             Matrix  1999
1                                    Cadena Perpetua  1994
2                                          Parasitos  2019
3                                Vengadores, Endgame  2019
4                                       Interstellar  2014
5                               Django Desencadenado  2012
6                                         El Padrino  1972
7                                El Caballero Oscuro  2008
8                           Erase Una Vez En America  1984
9  El Senyor de los Anillos, La Comunidad del Anillo  2001

In [40]:
# Your solution HERE !!!!  

def extract_year(peliculas_año):
    Name=[]
    Year=[]
    for peliculas in movies.values():
        for pelicula in peliculas:
            pel_comp=pelicula.split(" - ")
            Name.append(pel_comp[0].strip())
            Year.append(pel_comp[1].strip())
        diccionario={"Name": Name, "Year":Year}
        diccionario=pd.DataFrame(diccionario)
        return diccionario

In [41]:
movies = {'Name': ["Matrix - 1999", "Cadena Perpetua - 1994", "Parasitos - 2019", "Vengadores, Endgame - 2019", "Interstellar - 2014",
                   "Django Desencadenado - 2012", "El Padrino - 1972", "El Caballero Oscuro - 2008", "Erase Una Vez En America - 1984",
                   "El Senyor de los Anillos, La Comunidad del Anillo - 2001"]}
extract_year(movies)

                                                Name  Year
0                                             Matrix  1999
1                                    Cadena Perpetua  1994
2                                          Parasitos  2019
3                                Vengadores, Endgame  2019
4                                       Interstellar  2014
5                               Django Desencadenado  2012
6                                         El Padrino  1972
7                                El Caballero Oscuro  2008
8                           Erase Una Vez En America  1984
9  El Senyor de los Anillos, La Comunidad del Anillo  2001

## 02
- Crear una función que reciba un array de NumPy y devuelva otro en el cual estén marcados como True los elementos duplicados (a partir de la segunda ocurrencia), y como False los no repetidos o las primeras ocurrencias de los duplicados.

In [56]:
numbers = np.array([4, 4, 4, 3, 8, 1, 9, 6, 1, 5, 9, 4, 0, 2])
expected_output = np.array([False, True, True, False, False, False, False, False, True, False, True, True, False, False])
output = find_duplicates(numbers)   # This calls your function find_duplicates
print(output)
assert(np.array_equal(expected_output, output))  # This will fail if the result is not as expected

0     False
1      True
2      True
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10     True
11     True
12    False
13    False
dtype: bool

In [54]:
# Your solution HERE !!!!
def find_duplicates(lista_numeros):
    return pd.Series(numbers).duplicated()

In [55]:
find_duplicates(numbers)

0     False
1      True
2      True
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10     True
11     True
12    False
13    False
dtype: bool

## 03
- Resolución de dos sistemas de ecuaciones
    - $ A : \begin{cases} -9x +  4y = 20 \\ -7y + 16x = 80                         \end{cases}$
    
    - $ B : \begin{cases} x - 2y + 3z = 7 \\ 2x + y + z = 4 \\ -3x + 2y -2z = -10 \end{cases}$
- Verifica por código los resultados

In [62]:
# Your solution HERE !!!!
# Primer sistema de ecuaciones
A=[[-9, 4], [-7, 16]]
b=[20, 80]
solucion=np.linalg.solve(A, b)
print(solucion)

# Segundo sistema de ecuaciones
A=[[1,-2,3], [2,1,1], [-3,2,-2]]
b=[7,4,-10]
solucion=np.linalg.solve(A, b)
print(solucion)

[-0.  5.]
[ 2. -1.  1.]

## 04
- Crear un objeto Series con 10 elementos, que contenga más de un tipo básico, con índices de tipo string
- Demuestra que los datos con índices posicionales son los mismos que los obtenidos con índices semánticos, seleccionando a través de slicing, al menos 4 elementos de la serie anterior

In [79]:
# Your solution HERE !!!!
objeto=pd.Series([67, "Ordenador", 33.6, [1, 2, 3], "Pelicula", {"Numeros": [10, 20, 30], "Frutas":["Manzana", "Pera"]}, 89, 0, 90, 1000], index=["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"])
print(objeto[0]==objeto["a"])
print(objeto[1]==objeto["b"])
print(objeto[2]==objeto["c"])
print(objeto[3]==objeto["d"])

True
True
True
True

C:\Users\Acer Predator\AppData\Local\Temp\ipykernel_21476\4247231944.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(objeto[0]==objeto["a"])
C:\Users\Acer Predator\AppData\Local\Temp\ipykernel_21476\4247231944.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(objeto[1]==objeto["b"])
C:\Users\Acer Predator\AppData\Local\Temp\ipykernel_21476\4247231944.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(objeto[2]==objeto["c"])
C:\Users\Acer Predator\AppData\Local\Temp\ipykernel_21476\4247231944.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(objeto[3]==objeto["d"])

## 05
- Crear un DataFrame de dimensiones 10x10, con números aleatorios en el rango `[0,20]`
- Reemplazar todos aquellos elementos menores de 5 por NaN
- Averiguar cuantos elementos tienen Nan por fila

In [139]:
# Your solution HERE !!!!
matriz=pd.DataFrame(np.random.uniform(21, size=(10,10)))
display(matriz)
matriz=matriz.mask(matriz<5, np.nan)
suma=matriz.isna().sum(axis=1)
print(suma)

,0,1,2,3,4,5,6,7,8,9
0,1.038069,6.698939,18.549268,3.232923,9.995423,16.035726,3.173107,6.727604,18.015318,7.804887
1,7.627217,5.014178,16.045279,19.408965,16.039476,4.048850,16.594987,18.115119,20.040110,9.805849
2,17.692374,12.340269,20.485849,16.975220,10.143789,4.150806,12.616774,4.289253,9.125995,3.491349
3,13.756513,5.650185,9.530649,20.776771,6.759896,9.508195,20.648923,15.307374,11.272419,12.671746
4,9.785753,10.066849,19.470917,13.458884,17.710098,7.487147,5.754900,19.159967,12.825460,20.875702
5,11.771011,20.682909,1.297222,9.595916,17.283867,16.764427,16.463662,2.347594,2.945895,7.295544
6,4.913865,17.404972,19.862907,8.458238,10.457548,3.568579,4.659419,8.001231,13.377462,17.520518
7,20.316382,10.546312,14.033396,15.416166,17.134988,8.949801,18.833609,4.904287,16.173936,9.293321
8,17.217766,8.419583,17.497099,8.764310,8.874335,8.935091,1.937691,9.845285,20.385288,17.743952
9,20.083817,13.625312,7.101356,9.283038,14.512158,4.866512,9.751384,15.300672,11.863365,15.525124

0    3
1    1
2    3
3    0
4    0
5    3
6    3
7    1
8    1
9    1
dtype: int64

## 06
- Dada una lista de elementos, crea una función que devuelva un dataframe sin los elementos duplicados

In [200]:
serie = ['a','b','c','a','c','a','g']
expected_output = pd.DataFrame(['a','b','c','g'])
output = remove_duplicates(serie)   # This will call tour function remove_duplicates
display(output)
display(expected_output)
assert(expected_output.equals(output))  # This will fail if the result is not as expected

   0
0  a
1  b
2  c
3  g

   0
0  a
1  b
2  c
3  g

In [199]:
# Your solution HERE !!!!
def remove_duplicates(serie):
    sin_duplicados=pd.DataFrame(serie).drop_duplicates(inplace=False)
    sin_duplicados=sin_duplicados.reset_index(drop=True)
    return sin_duplicados

## 07 - 1pt
- Escribir un generador `frange` que simule el comportamiento de la función `arange` de NumPy
- Esta función cada vez que se invoque debe devolver valores espaciados uniformemente a partir de un valor inicial. Se debe proveer a dicha función un valor inicial para la secuencia de números y un valor para el step
- Debe soportar valores númericos en coma flotante
- La función potencialmente se puede llamar un número infinito de veces
- Usando plain Python, sin ninguna librería

In [12]:
import math

init = 10.6
step = 0.8
g = frange(init, step)  # This calls your function frange

iters = 10
numbers = [next(g) for n in range(iters)]
for i, n in enumerate(numbers):
    assert(math.isclose(n, init + (step * i)))  # This will fail if the range is not properly created
print(numbers)

[10.6, 11.4, 12.2, 13.0, 13.8, 14.6, 15.4, 16.2, 17.0, 17.8]

In [9]:
# Your solution HERE !!!!
def frange(inicial, paso):
    iters=10
    lista=[]
    i=0
    for n in range(iters):
        lista.append(inicial+(paso*i))
        i+=1
    return iter(lista)

In [10]:
frange(init, step)

## 08
- Crear una función que reciba una Serie de Pandas y devuelva esa misma serie, reemplazando los espacios en blanco por el carácter menos frecuente en dicha serie.

In [ ]:
serie = pd.Series(list('bba cabc faabba aacbbfe'))
expected_output = pd.Series(list('bbaecabcefaabbaeaacbbfe'))
output = clean_whitespace_replace(serie)  # This calls your function clean_whitespace_replace
assert(expected_output.equals(output))  # This will fail if result is not as expected

In [ ]:
# Your solution HERE !!!!
def clean_whitespace_replace(serie):
    diccionario={}
    for letra in serie:
        diccionario[letra]+=1
    for letra in serie:
        if letra ==" ":
            letra.

In [ ]:
clean_whitespace_replace(serie)